// <auto-generated />
using System;
using ELearning.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ELearning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ELearningDbContext))]
    [Migration("20261009094351_AddVideoLessons")]
    partial class AddVideoLessons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("QuestionCodeSequence");

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AnswerNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AttemptQuestionId")
                        .HasColumnType("uuid");

                    b.Property<long>("ClientSeq")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMarkedForReview")
                        .HasColumnType("boolean");

                    b.Property<string>("ManualComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ManualGradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManualGradedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ManualScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SaveCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_AttemptAnswers");

                    b.HasIndex("AttemptQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttemptAnswers_Question");

                    b.HasIndex("ManualGradedBy");

                    b.ToTable("AttemptAnswers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswerOption", b =>
                {
                    b.Property<Guid>("AttemptAnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OptionCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.HasKey("AttemptAnswerId", "OptionCode")
                        .HasName("PK_AttemptAnswerOptions");

                    b.ToTable("AttemptAnswerOptions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClientTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("ServerTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_AttemptEvents");

                    b.HasIndex("AttemptId", "ServerTime")
                        .HasDatabaseName("IX_AttemptEvents_Attempt");

                    b.ToTable("AttemptEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttemptEvents_Type", "\"EventType\" IN ('VISIBILITY_HIDDEN','VISIBILITY_VISIBLE','WINDOW_BLUR','WINDOW_FOCUS','FULLSCREEN_EXIT','OFFLINE','ONLINE','MULTI_TAB_DETECTED','PAGE_RELOAD','PASTE')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("OptionOrder")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_AttemptQuestions");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("AttemptId", "ExamQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttemptQuestions_Question");

                    b.HasIndex("AttemptId", "QuestionOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttemptQuestions_Order");

                    b.ToTable("AttemptQuestions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartedIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("StartedUserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SubmitReason")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("TimeExtensionMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ExamAttempts");

                    b.HasIndex("CancelledBy");

                    b.HasIndex("ExpiredAt")
                        .HasDatabaseName("IX_ExamAttempts_InProgress_Expired")
                        .HasFilter("\"Status\" = 'IN_PROGRESS'");

                    b.HasIndex("ExamId", "Status")
                        .HasDatabaseName("IX_ExamAttempts_Exam");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ExamId", "Status"), new[] { "UserId", "SubmittedAt" });

                    b.HasIndex("ExamVersionId", "Status")
                        .HasDatabaseName("IX_ExamAttempts_Version");

                    b.HasIndex("UserId", "ExamId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamAttempts_OneInProgress")
                        .HasFilter("\"Status\" = 'IN_PROGRESS'");

                    b.HasIndex("UserId", "ExamId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamAttempts_User_Exam_Number");

                    b.ToTable("ExamAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAttempts_Status", "\"Status\" IN ('IN_PROGRESS','SUBMITTED','AUTO_SUBMITTED','CANCELLED')");

                            t.HasCheckConstraint("CK_ExamAttempts_SubmitReason", "\"SubmitReason\" IN ('STUDENT','TIME_EXPIRED','FORCED_BY_ADMIN')");

                            t.HasCheckConstraint("CK_ExamAttempts_Submitted", "(\"Status\" IN ('SUBMITTED','AUTO_SUBMITTED') AND \"SubmittedAt\" IS NOT NULL AND \"SubmitReason\" IS NOT NULL) OR (\"Status\" IN ('IN_PROGRESS','CANCELLED'))");

                            t.HasCheckConstraint("CK_ExamAttempts_Time", "\"ExpiredAt\" > \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_AuditLogs");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditLogs_User");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Classes.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SchoolYear")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Classrooms");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Classrooms_Code");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Classrooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Classrooms_Dates", "\"EndDate\" IS NULL OR \"StartDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Classes.ClassroomStudent", b =>
                {
                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClassroomId", "UserId")
                        .HasName("PK_ClassroomStudents");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ClassroomStudents_User");

                    b.ToTable("ClassroomStudents", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.AnswerKeyCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CorrectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CorrectedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewKeyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldKeyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id")
                        .HasName("PK_AnswerKeyCorrections");

                    b.HasIndex("CorrectedBy");

                    b.HasIndex("ExamQuestionId")
                        .HasDatabaseName("IX_AnswerKeyCorrections_Question");

                    b.ToTable("AnswerKeyCorrections", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnswerKeyCorrections_Type", "\"CorrectionType\" IN ('ANSWER_KEY','VOID')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RetakeScoringPolicy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Exams");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Exams_Code");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Exams_Status");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status"), new[] { "StartAt", "EndAt", "AccessMode" });

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Exams", null, t =>
                        {
                            t.HasCheckConstraint("CK_Exams_AccessMode", "\"AccessMode\" IN ('PUBLIC','ASSIGNED')");

                            t.HasCheckConstraint("CK_Exams_MaxAttempts", "\"MaxAttempts\" BETWEEN 1 AND 50");

                            t.HasCheckConstraint("CK_Exams_RetakeScoring", "\"RetakeScoringPolicy\" IN ('HIGHEST','LATEST')");

                            t.HasCheckConstraint("CK_Exams_Status", "\"Status\" IN ('DRAFT','PUBLISHED','CLOSED')");

                            t.HasCheckConstraint("CK_Exams_Window", "\"StartAt\" IS NULL OR \"EndAt\" IS NULL OR \"StartAt\" < \"EndAt\"");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ExamAssignments");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("IX_ExamAssignments_ClassroomId")
                        .HasFilter("\"ClassroomId\" IS NOT NULL");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_ExamAssignments_GroupId")
                        .HasFilter("\"GroupId\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ExamAssignments_UserId")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.HasIndex("ExamId", "ClassroomId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamAssignments_Classroom")
                        .HasFilter("\"ClassroomId\" IS NOT NULL");

                    b.HasIndex("ExamId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamAssignments_Group")
                        .HasFilter("\"GroupId\" IS NOT NULL");

                    b.HasIndex("ExamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamAssignments_User")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("ExamAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAssignments_Target", "(CASE WHEN \"GroupId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"UserId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"ClassroomId\" IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamPoolRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("DrawCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("RuleOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScorePerQuestion")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK_ExamPoolRules");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExamVersionId", "RuleOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamPoolRules_Order");

                    b.ToTable("ExamPoolRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamPoolRules_Difficulty", "\"Difficulty\" IN ('EASY','MEDIUM','HARD')");

                            t.HasCheckConstraint("CK_ExamPoolRules_DrawCount", "\"DrawCount\" BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_ExamPoolRules_Score", "\"ScorePerQuestion\" > 0");

                            t.HasCheckConstraint("CK_ExamPoolRules_Type", "\"QuestionType\" IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','FILL_IN','ESSAY')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerDataType")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CopiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CorrectAnswerNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IgnoreAccent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NumericTolerance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<bool>("PartialScoring")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PoolRuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("SourceQuestionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("SourceRowVersion")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VoidedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ExamQuestions");

                    b.HasIndex("PoolRuleId")
                        .HasDatabaseName("IX_ExamQuestions_PoolRule")
                        .HasFilter("\"PoolRuleId\" IS NOT NULL");

                    b.HasIndex("SourceQuestionId");

                    b.HasIndex("VoidedBy");

                    b.HasIndex("ExamVersionId", "QuestionOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamQuestions_Order");

                    b.HasIndex("ExamVersionId", "SourceQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamQuestions_Source")
                        .HasFilter("\"SourceQuestionId\" IS NOT NULL");

                    b.ToTable("ExamQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamQuestions_AnswerDataType", "\"AnswerDataType\" IN ('TEXT','NUMBER')");

                            t.HasCheckConstraint("CK_ExamQuestions_ContentFormat", "\"ContentFormat\" IN ('PLAIN','MARKDOWN')");

                            t.HasCheckConstraint("CK_ExamQuestions_Score", "\"Score\" > 0");

                            t.HasCheckConstraint("CK_ExamQuestions_Type", "\"QuestionType\" IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','FILL_IN','ESSAY')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionAcceptedAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ExamQuestionAcceptedAnswers");

                    b.HasIndex("ExamQuestionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamQuestionAcceptedAnswers_Order");

                    b.ToTable("ExamQuestionAcceptedAnswers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id")
                        .HasName("PK_ExamQuestionOptions");

                    b.HasIndex("ExamQuestionId", "OptionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamQuestionOptions_Code");

                    b.ToTable("ExamQuestionOptions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamUserOverride", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExtraAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ExamId", "UserId")
                        .HasName("PK_ExamUserOverrides");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("ExamUserOverrides", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamUserOverrides_Extra", "\"ExtraAttempts\" BETWEEN 0 AND 50");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("PassPercentage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewPolicy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ScoreVisibility")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("ShuffleOptions")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_ExamVersions");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("ExamId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamVersions_Number");

                    b.HasIndex(new[] { "ExamId" }, "UX_ExamVersions_OneDraft")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'DRAFT'");

                    b.HasIndex(new[] { "ExamId" }, "UX_ExamVersions_OnePublished")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'PUBLISHED'");

                    b.ToTable("ExamVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamVersions_Duration", "\"DurationMinutes\" BETWEEN 1 AND 600");

                            t.HasCheckConstraint("CK_ExamVersions_Pass", "\"PassPercentage\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_ExamVersions_ReviewPolicy", "\"ReviewPolicy\" IN ('NEVER','AFTER_SUBMIT','AFTER_EXAM_END','AFTER_LAST_ATTEMPT')");

                            t.HasCheckConstraint("CK_ExamVersions_ScoreVisibility", "\"ScoreVisibility\" IN ('IMMEDIATE','AFTER_EXAM_END','HIDDEN')");

                            t.HasCheckConstraint("CK_ExamVersions_Status", "\"Status\" IN ('DRAFT','PUBLISHED','ARCHIVED')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id")
                        .HasName("PK_Permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Permissions_Code");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_RefreshTokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_RefreshTokens_Family");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_User");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_RevokedReason", "\"RevokedReason\" IN ('ROTATED','LOGOUT','REUSE_DETECTED','PASSWORD_CHANGED','USER_DISABLED','ADMIN')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Code");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK_RolePermissions");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_NormalizedUserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id")
                        .HasName("PK_UserGroups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserGroups_Code");

                    b.HasIndex("CreatedBy");

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId", "UserId")
                        .HasName("PK_UserGroupMembers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserGroupMembers_User");

                    b.ToTable("UserGroupMembers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Media.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_MediaFiles");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("UQ_MediaFiles_Sha256");

                    b.ToTable("MediaFiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaFiles_ContentType", "\"ContentType\" IN ('image/png','image/jpeg','image/gif','image/webp')");

                            t.HasCheckConstraint("CK_MediaFiles_Size", "\"SizeBytes\" > 0");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerDataType")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal?>("CorrectAnswerNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefaultScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IgnoreAccent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NumericTolerance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<bool>("PartialScoring")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Questions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Questions_Code");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("CategoryId", "QuestionType")
                        .HasDatabaseName("IX_Questions_Category_Type");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId", "QuestionType"), new[] { "IsActive" });

                    b.ToTable("Questions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Questions_AnswerDataType", "\"AnswerDataType\" IN ('TEXT','NUMBER')");

                            t.HasCheckConstraint("CK_Questions_ContentFormat", "\"ContentFormat\" IN ('PLAIN','MARKDOWN')");

                            t.HasCheckConstraint("CK_Questions_Difficulty", "\"Difficulty\" IN ('EASY','MEDIUM','HARD')");

                            t.HasCheckConstraint("CK_Questions_FillIn", "(\"QuestionType\" = 'FILL_IN' AND \"AnswerDataType\" IS NOT NULL) OR (\"QuestionType\" <> 'FILL_IN' AND \"AnswerDataType\" IS NULL)");

                            t.HasCheckConstraint("CK_Questions_Number", "\"AnswerDataType\" IS NULL OR \"AnswerDataType\" <> 'NUMBER' OR (\"CorrectAnswerNumber\" IS NOT NULL AND \"NumericTolerance\" IS NOT NULL AND \"NumericTolerance\" >= 0)");

                            t.HasCheckConstraint("CK_Questions_Score", "\"DefaultScore\" > 0");

                            t.HasCheckConstraint("CK_Questions_Type", "\"QuestionType\" IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','FILL_IN','ESSAY')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionAcceptedAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_QuestionAcceptedAnswers");

                    b.HasIndex("QuestionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionAcceptedAnswers_Order");

                    b.ToTable("QuestionAcceptedAnswers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_QuestionCategories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionCategories_Code");

                    b.HasIndex("CreatedBy");

                    b.ToTable("QuestionCategories", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_QuestionOptions");

                    b.HasIndex("QuestionId", "OptionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionOptions_Code");

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK_QuestionTags");

                    b.HasIndex("Tag")
                        .HasDatabaseName("IX_QuestionTags_Tag");

                    b.HasIndex("QuestionId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionTags_Tag");

                    b.ToTable("QuestionTags", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnsweredCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GradingRevision")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("PendingManualCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("RegradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalQuestion")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ExamResults");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamResults_Attempt");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("IX_ExamResults_Exam");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ExamId"), new[] { "UserId", "TotalScore", "Percentage", "Passed", "SubmittedAt" });

                    b.HasIndex("ExamVersionId");

                    b.HasIndex("UserId", "SubmittedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ExamResults_User");

                    b.ToTable("ExamResults", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamResults_MaxScore", "\"MaxScore\" > 0");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResultHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AnswerKeyCorrectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("GradingRevision")
                        .HasColumnType("integer");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_ExamResultHistory");

                    b.HasIndex("AnswerKeyCorrectionId");

                    b.HasIndex("ExamResultId")
                        .HasDatabaseName("IX_ExamResultHistory_Result");

                    b.ToTable("ExamResultHistory", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Videos.VideoLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("YoutubeVideoId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK_VideoLessons");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_VideoLessons_CategoryId");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("IX_VideoLessons_ClassroomId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("VideoLessons", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.AttemptQuestion", null)
                        .WithOne("Answer")
                        .HasForeignKey("ELearning.Domain.Attempts.AttemptAnswer", "AttemptQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptAnswers_Question");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ManualGradedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AttemptAnswers_ManualGradedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswerOption", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.AttemptAnswer", null)
                        .WithMany("SelectedOptions")
                        .HasForeignKey("AttemptAnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptAnswerOptions_Answer");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptEvent", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.ExamAttempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptEvents_Attempt");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptQuestion", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.ExamAttempt", null)
                        .WithMany("Questions")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptQuestions_Attempt");

                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptQuestions_ExamQuestion");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.ExamAttempt", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamAttempts_CancelledBy");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAttempts_Exam");

                    b.HasOne("ELearning.Domain.Exams.ExamVersion", null)
                        .WithMany()
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAttempts_Version");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAttempts_User");
                });

            modelBuilder.Entity("ELearning.Domain.Classes.Classroom", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Classrooms_CreatedBy");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Classrooms_UpdatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Classes.ClassroomStudent", b =>
                {
                    b.HasOne("ELearning.Domain.Classes.Classroom", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ClassroomStudents_Classroom");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ClassroomStudents_User");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.AnswerKeyCorrection", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CorrectedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AnswerKeyCorrections_By");

                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AnswerKeyCorrections_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Exams_CreatedBy");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Exams_UpdatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamAssignment", b =>
                {
                    b.HasOne("ELearning.Domain.Classes.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamAssignments_Classroom");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAssignments_CreatedBy");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAssignments_Exam");

                    b.HasOne("ELearning.Domain.Identity.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamAssignments_Group");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamAssignments_User");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamPoolRule", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.QuestionCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamPoolRules_Category");

                    b.HasOne("ELearning.Domain.Exams.ExamVersion", null)
                        .WithMany("PoolRules")
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamPoolRules_Version");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.ExamVersion", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestions_Version");

                    b.HasOne("ELearning.Domain.Exams.ExamPoolRule", null)
                        .WithMany()
                        .HasForeignKey("PoolRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamQuestions_PoolRule");

                    b.HasOne("ELearning.Domain.Questions.Question", null)
                        .WithMany()
                        .HasForeignKey("SourceQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamQuestions_SourceQuestion");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("VoidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamQuestions_VoidedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionAcceptedAnswer", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany("AcceptedAnswers")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestionAcceptedAnswers_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionOption", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestionOptions_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamUserOverride", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamUserOverrides_Exam");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamUserOverrides_UpdatedBy");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamUserOverrides_User");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamVersion", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamVersions_CreatedBy");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany("Versions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamVersions_Exam");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PublishedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamVersions_PublishedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_User");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Permission");

                    b.HasOne("ELearning.Domain.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Role");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroup", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroups_CreatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroupMember", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.UserGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroupMembers_Group");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroupMembers_User");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Role");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_User");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ELearning.Domain.Media.MediaFile", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MediaFiles_CreatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.Question", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.QuestionCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Questions_Category");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Questions_CreatedBy");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Questions_UpdatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionAcceptedAnswer", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.Question", null)
                        .WithMany("AcceptedAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionAcceptedAnswers_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionCategory", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionCategories_CreatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionOption", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionOptions_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionTag", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.Question", null)
                        .WithMany("Tags")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionTags_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResult", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.ExamAttempt", null)
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Results.ExamResult", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_Attempt");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_Exam");

                    b.HasOne("ELearning.Domain.Exams.ExamVersion", null)
                        .WithMany()
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_Version");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_User");
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResultHistory", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.AnswerKeyCorrection", null)
                        .WithMany()
                        .HasForeignKey("AnswerKeyCorrectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResultHistory_Correction");

                    b.HasOne("ELearning.Domain.Results.ExamResult", null)
                        .WithMany("History")
                        .HasForeignKey("ExamResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResultHistory_Result");
                });

            modelBuilder.Entity("ELearning.Domain.Videos.VideoLesson", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.QuestionCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_VideoLessons_Category");

                    b.HasOne("ELearning.Domain.Classes.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_VideoLessons_Classroom");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VideoLessons_CreatedBy");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_VideoLessons_UpdatedBy");

                    b.Navigation("Category");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptQuestion", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.ExamAttempt", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ELearning.Domain.Classes.Classroom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.Navigation("AcceptedAnswers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamVersion", b =>
                {
                    b.Navigation("PoolRules");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.User", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.Question", b =>
                {
                    b.Navigation("AcceptedAnswers");

                    b.Navigation("Options");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResult", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
