// <auto-generated />
using System;
using ELearning.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELearning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ELearningDbContext))]
    [Migration("20260929015715_QuestionPoolAndTags")]
    partial class QuestionPoolAndTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("QuestionCodeSequence");

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AnswerNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<string>("AnswerText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("AttemptQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ClientSeq")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMarkedForReview")
                        .HasColumnType("bit");

                    b.Property<int>("SaveCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_AttemptAnswers");

                    b.HasIndex("AttemptQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttemptAnswers_Question");

                    b.ToTable("AttemptAnswers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswerOption", b =>
                {
                    b.Property<Guid>("AttemptAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("AttemptAnswerId", "OptionCode")
                        .HasName("PK_AttemptAnswerOptions");

                    b.ToTable("AttemptAnswerOptions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClientTime")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("ServerTime")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id")
                        .HasName("PK_AttemptEvents");

                    b.HasIndex("AttemptId", "ServerTime")
                        .HasDatabaseName("IX_AttemptEvents_Attempt");

                    b.ToTable("AttemptEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttemptEvents_Type", "[EventType] IN ('VISIBILITY_HIDDEN','VISIBILITY_VISIBLE','WINDOW_BLUR','WINDOW_FOCUS','FULLSCREEN_EXIT','OFFLINE','ONLINE','MULTI_TAB_DETECTED','PAGE_RELOAD','PASTE')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionOrder")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_AttemptQuestions");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("AttemptId", "ExamQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttemptQuestions_Question");

                    b.HasIndex("AttemptId", "QuestionOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttemptQuestions_Order");

                    b.ToTable("AttemptQuestions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("StartedIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("StartedUserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SubmitReason")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("SubmittedIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("TimeExtensionMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_ExamAttempts");

                    b.HasIndex("CancelledBy");

                    b.HasIndex("ExpiredAt")
                        .HasDatabaseName("IX_ExamAttempts_InProgress_Expired")
                        .HasFilter("[Status] = 'IN_PROGRESS'");

                    b.HasIndex("ExamId", "Status")
                        .HasDatabaseName("IX_ExamAttempts_Exam");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ExamId", "Status"), new[] { "UserId", "SubmittedAt" });

                    b.HasIndex("ExamVersionId", "Status")
                        .HasDatabaseName("IX_ExamAttempts_Version");

                    b.HasIndex("UserId", "ExamId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamAttempts_OneInProgress")
                        .HasFilter("[Status] = 'IN_PROGRESS'");

                    b.HasIndex("UserId", "ExamId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamAttempts_User_Exam_Number");

                    b.ToTable("ExamAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAttempts_Status", "[Status] IN ('IN_PROGRESS','SUBMITTED','AUTO_SUBMITTED','CANCELLED')");

                            t.HasCheckConstraint("CK_ExamAttempts_SubmitReason", "[SubmitReason] IN ('STUDENT','TIME_EXPIRED','FORCED_BY_ADMIN')");

                            t.HasCheckConstraint("CK_ExamAttempts_Submitted", "([Status] IN ('SUBMITTED','AUTO_SUBMITTED') AND [SubmittedAt] IS NOT NULL AND [SubmitReason] IS NOT NULL) OR ([Status] IN ('IN_PROGRESS','CANCELLED'))");

                            t.HasCheckConstraint("CK_ExamAttempts_Time", "[ExpiredAt] > [StartedAt]");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_AuditLogs");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditLogs_User");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.AnswerKeyCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AffectedAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CorrectedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CorrectedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewKeyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldKeyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_AnswerKeyCorrections");

                    b.HasIndex("CorrectedBy");

                    b.HasIndex("ExamQuestionId")
                        .HasDatabaseName("IX_AnswerKeyCorrections_Question");

                    b.ToTable("AnswerKeyCorrections", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnswerKeyCorrections_Type", "[CorrectionType] IN ('ANSWER_KEY','VOID')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RetakeScoringPolicy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Exams");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Exams_Code");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Exams_Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status"), new[] { "StartAt", "EndAt", "AccessMode" });

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Exams", null, t =>
                        {
                            t.HasCheckConstraint("CK_Exams_AccessMode", "[AccessMode] IN ('PUBLIC','ASSIGNED')");

                            t.HasCheckConstraint("CK_Exams_MaxAttempts", "[MaxAttempts] BETWEEN 1 AND 50");

                            t.HasCheckConstraint("CK_Exams_RetakeScoring", "[RetakeScoringPolicy] IN ('HIGHEST','LATEST')");

                            t.HasCheckConstraint("CK_Exams_Status", "[Status] IN ('DRAFT','PUBLISHED','CLOSED')");

                            t.HasCheckConstraint("CK_Exams_Window", "[StartAt] IS NULL OR [EndAt] IS NULL OR [StartAt] < [EndAt]");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_ExamAssignments");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_ExamAssignments_GroupId")
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ExamAssignments_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.HasIndex("ExamId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamAssignments_Group")
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.HasIndex("ExamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamAssignments_User")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("ExamAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAssignments_Target", "([GroupId] IS NULL AND [UserId] IS NOT NULL) OR ([GroupId] IS NOT NULL AND [UserId] IS NULL)");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamPoolRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("DrawCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("RuleOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("ScorePerQuestion")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_ExamPoolRules");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExamVersionId", "RuleOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamPoolRules_Order");

                    b.ToTable("ExamPoolRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamPoolRules_Difficulty", "[Difficulty] IN ('EASY','MEDIUM','HARD')");

                            t.HasCheckConstraint("CK_ExamPoolRules_DrawCount", "[DrawCount] BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_ExamPoolRules_Score", "[ScorePerQuestion] > 0");

                            t.HasCheckConstraint("CK_ExamPoolRules_Type", "[QuestionType] IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','FILL_IN')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerDataType")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CopiedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("CorrectAnswerNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IgnoreAccent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NumericTolerance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<Guid?>("PoolRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("SourceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("SourceRowVersion")
                        .HasColumnType("binary(8)");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("VoidedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_ExamQuestions");

                    b.HasIndex("PoolRuleId")
                        .HasDatabaseName("IX_ExamQuestions_PoolRule")
                        .HasFilter("[PoolRuleId] IS NOT NULL");

                    b.HasIndex("SourceQuestionId");

                    b.HasIndex("VoidedBy");

                    b.HasIndex("ExamVersionId", "QuestionOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamQuestions_Order");

                    b.HasIndex("ExamVersionId", "SourceQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamQuestions_Source")
                        .HasFilter("[SourceQuestionId] IS NOT NULL");

                    b.ToTable("ExamQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamQuestions_AnswerDataType", "[AnswerDataType] IN ('TEXT','NUMBER')");

                            t.HasCheckConstraint("CK_ExamQuestions_ContentFormat", "[ContentFormat] IN ('PLAIN','MARKDOWN')");

                            t.HasCheckConstraint("CK_ExamQuestions_Score", "[Score] > 0");

                            t.HasCheckConstraint("CK_ExamQuestions_Type", "[QuestionType] IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','FILL_IN')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionAcceptedAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_ExamQuestionAcceptedAnswers");

                    b.HasIndex("ExamQuestionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamQuestionAcceptedAnswers_Order");

                    b.ToTable("ExamQuestionAcceptedAnswers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK_ExamQuestionOptions");

                    b.HasIndex("ExamQuestionId", "OptionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamQuestionOptions_Code");

                    b.ToTable("ExamQuestionOptions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamUserOverride", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExtraAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExamId", "UserId")
                        .HasName("PK_ExamUserOverrides");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("ExamUserOverrides", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamUserOverrides_Extra", "[ExtraAttempts] BETWEEN 0 AND 50");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PassPercentage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<string>("ReviewPolicy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScoreVisibility")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("ShuffleOptions")
                        .HasColumnType("bit");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ExamVersions");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("ExamId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamVersions_Number");

                    b.HasIndex(new[] { "ExamId" }, "UX_ExamVersions_OneDraft")
                        .IsUnique()
                        .HasFilter("[Status] = 'DRAFT'");

                    b.HasIndex(new[] { "ExamId" }, "UX_ExamVersions_OnePublished")
                        .IsUnique()
                        .HasFilter("[Status] = 'PUBLISHED'");

                    b.ToTable("ExamVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamVersions_Duration", "[DurationMinutes] BETWEEN 1 AND 600");

                            t.HasCheckConstraint("CK_ExamVersions_Pass", "[PassPercentage] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_ExamVersions_ReviewPolicy", "[ReviewPolicy] IN ('NEVER','AFTER_SUBMIT','AFTER_EXAM_END','AFTER_LAST_ATTEMPT')");

                            t.HasCheckConstraint("CK_ExamVersions_ScoreVisibility", "[ScoreVisibility] IN ('IMMEDIATE','AFTER_EXAM_END','HIDDEN')");

                            t.HasCheckConstraint("CK_ExamVersions_Status", "[Status] IN ('DRAFT','PUBLISHED','ARCHIVED')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Permissions_Code");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_RefreshTokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_RefreshTokens_Family");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_User");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_RevokedReason", "[RevokedReason] IN ('ROTATED','LOGOUT','REUSE_DETECTED','PASSWORD_CHANGED','USER_DISABLED','ADMIN')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Code");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK_RolePermissions");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_NormalizedUserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_UserGroups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserGroups_Code");

                    b.HasIndex("CreatedBy");

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("GroupId", "UserId")
                        .HasName("PK_UserGroupMembers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserGroupMembers_User");

                    b.ToTable("UserGroupMembers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerDataType")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<decimal?>("CorrectAnswerNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DefaultScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IgnoreAccent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NumericTolerance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(30,10)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Questions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Questions_Code");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("CategoryId", "QuestionType")
                        .HasDatabaseName("IX_Questions_Category_Type");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId", "QuestionType"), new[] { "IsActive" });

                    b.ToTable("Questions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Questions_AnswerDataType", "[AnswerDataType] IN ('TEXT','NUMBER')");

                            t.HasCheckConstraint("CK_Questions_ContentFormat", "[ContentFormat] IN ('PLAIN','MARKDOWN')");

                            t.HasCheckConstraint("CK_Questions_Difficulty", "[Difficulty] IN ('EASY','MEDIUM','HARD')");

                            t.HasCheckConstraint("CK_Questions_FillIn", "([QuestionType] = 'FILL_IN' AND [AnswerDataType] IS NOT NULL) OR ([QuestionType] <> 'FILL_IN' AND [AnswerDataType] IS NULL)");

                            t.HasCheckConstraint("CK_Questions_Number", "[AnswerDataType] IS NULL OR [AnswerDataType] <> 'NUMBER' OR ([CorrectAnswerNumber] IS NOT NULL AND [NumericTolerance] IS NOT NULL AND [NumericTolerance] >= 0)");

                            t.HasCheckConstraint("CK_Questions_Score", "[DefaultScore] > 0");

                            t.HasCheckConstraint("CK_Questions_Type", "[QuestionType] IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','FILL_IN')");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionAcceptedAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_QuestionAcceptedAnswers");

                    b.HasIndex("QuestionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionAcceptedAnswers_Order");

                    b.ToTable("QuestionAcceptedAnswers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id")
                        .HasName("PK_QuestionCategories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionCategories_Code");

                    b.HasIndex("CreatedBy");

                    b.ToTable("QuestionCategories", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_QuestionOptions");

                    b.HasIndex("QuestionId", "OptionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionOptions_Code");

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_QuestionTags");

                    b.HasIndex("Tag")
                        .HasDatabaseName("IX_QuestionTags_Tag");

                    b.HasIndex("QuestionId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuestionTags_Tag");

                    b.ToTable("QuestionTags", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnsweredCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("GradingRevision")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("Passed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("RegradedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("TotalQuestion")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_ExamResults");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExamResults_Attempt");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("IX_ExamResults_Exam");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ExamId"), new[] { "UserId", "TotalScore", "Percentage", "Passed", "SubmittedAt" });

                    b.HasIndex("ExamVersionId");

                    b.HasIndex("UserId", "SubmittedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ExamResults_User");

                    b.ToTable("ExamResults", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamResults_MaxScore", "[MaxScore] > 0");
                        });
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResultHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AnswerKeyCorrectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GradingRevision")
                        .HasColumnType("int");

                    b.Property<bool?>("Passed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_ExamResultHistory");

                    b.HasIndex("AnswerKeyCorrectionId");

                    b.HasIndex("ExamResultId")
                        .HasDatabaseName("IX_ExamResultHistory_Result");

                    b.ToTable("ExamResultHistory", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.AttemptQuestion", null)
                        .WithOne("Answer")
                        .HasForeignKey("ELearning.Domain.Attempts.AttemptAnswer", "AttemptQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptAnswers_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswerOption", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.AttemptAnswer", null)
                        .WithMany("SelectedOptions")
                        .HasForeignKey("AttemptAnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptAnswerOptions_Answer");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptEvent", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.ExamAttempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptEvents_Attempt");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptQuestion", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.ExamAttempt", null)
                        .WithMany("Questions")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptQuestions_Attempt");

                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptQuestions_ExamQuestion");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.ExamAttempt", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamAttempts_CancelledBy");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAttempts_Exam");

                    b.HasOne("ELearning.Domain.Exams.ExamVersion", null)
                        .WithMany()
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAttempts_Version");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAttempts_User");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.AnswerKeyCorrection", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CorrectedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AnswerKeyCorrections_By");

                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AnswerKeyCorrections_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Exams_CreatedBy");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Exams_UpdatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamAssignment", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAssignments_CreatedBy");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAssignments_Exam");

                    b.HasOne("ELearning.Domain.Identity.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamAssignments_Group");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamAssignments_User");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamPoolRule", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.QuestionCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamPoolRules_Category");

                    b.HasOne("ELearning.Domain.Exams.ExamVersion", null)
                        .WithMany("PoolRules")
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamPoolRules_Version");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.ExamVersion", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestions_Version");

                    b.HasOne("ELearning.Domain.Exams.ExamPoolRule", null)
                        .WithMany()
                        .HasForeignKey("PoolRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamQuestions_PoolRule");

                    b.HasOne("ELearning.Domain.Questions.Question", null)
                        .WithMany()
                        .HasForeignKey("SourceQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamQuestions_SourceQuestion");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("VoidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamQuestions_VoidedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionAcceptedAnswer", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany("AcceptedAnswers")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestionAcceptedAnswers_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionOption", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestionOptions_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamUserOverride", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamUserOverrides_Exam");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamUserOverrides_UpdatedBy");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamUserOverrides_User");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamVersion", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamVersions_CreatedBy");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany("Versions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamVersions_Exam");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PublishedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExamVersions_PublishedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_User");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Permission");

                    b.HasOne("ELearning.Domain.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Role");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroup", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroups_CreatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroupMember", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.UserGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroupMembers_Group");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroupMembers_User");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Role");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_User");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.Question", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.QuestionCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Questions_Category");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Questions_CreatedBy");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Questions_UpdatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionAcceptedAnswer", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.Question", null)
                        .WithMany("AcceptedAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionAcceptedAnswers_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionCategory", b =>
                {
                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionCategories_CreatedBy");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionOption", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionOptions_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.QuestionTag", b =>
                {
                    b.HasOne("ELearning.Domain.Questions.Question", null)
                        .WithMany("Tags")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionTags_Question");
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResult", b =>
                {
                    b.HasOne("ELearning.Domain.Attempts.ExamAttempt", null)
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Results.ExamResult", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_Attempt");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_Exam");

                    b.HasOne("ELearning.Domain.Exams.ExamVersion", null)
                        .WithMany()
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_Version");

                    b.HasOne("ELearning.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResults_User");
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResultHistory", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.AnswerKeyCorrection", null)
                        .WithMany()
                        .HasForeignKey("AnswerKeyCorrectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResultHistory_Correction");

                    b.HasOne("ELearning.Domain.Results.ExamResult", null)
                        .WithMany("History")
                        .HasForeignKey("ExamResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExamResultHistory_Result");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.AttemptQuestion", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();
                });

            modelBuilder.Entity("ELearning.Domain.Attempts.ExamAttempt", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.Navigation("AcceptedAnswers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamVersion", b =>
                {
                    b.Navigation("PoolRules");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.User", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ELearning.Domain.Identity.UserGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ELearning.Domain.Questions.Question", b =>
                {
                    b.Navigation("AcceptedAnswers");

                    b.Navigation("Options");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ELearning.Domain.Results.ExamResult", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
